version: '3'

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: pikapikachu
      MYSQL_DATABASE: dsa3101
    ports:
      - "3307:3306"

  api:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db